#! /bin/sh

#xmodmap ~/.xmodmap
#xset m 2 0
#xset r rate 140 60

#/home/jdm/.fehbg

#sxhkd &
#plank &
#compton &


bspc config focus_follows_pointer true
bspc config border_width 10

#bspc monitor -d I II III IV
bspc monitor -d one two three four

bspc config border_width         0
bspc config window_gap           0



#bspc config split_ratio          0.375
#bspc config split_ratio          0.271
bspc config split_ratio          0.4
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#444444"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


#polybar bspc &
polybar bottom &
